### ISSUE TITLE
ext_translation doesn't exist

### ISSUE THREAD

**Issue by mkalisz77** [Simettric/DoctrineTranslatableFormBundle#5] opened 2016-12-30 13:00 UTC
I have Translation method set as Personal (custom translation table).

```
<?php
namespace AppBundle\Entity;

use Gedmo\Translatable\Entity\MappedSuperclass\AbstractPersonalTranslation;

/**
 * @ORM\Entity
 * @ORM\Table( name="zc_content_translations",
 *   uniqueConstraints={@ORM\UniqueConstraint(name="zc_content_trans_idx", columns={
 *         "locale", "object_id", "field"
 *   })}
 * )
 * @ORM\Entity(repositoryClass="AppBundle\Repository\ContentTranslationRepository")
 * @Gedmo\Loggable(logEntryClass="AppBundle\Entity\LogEntry")
 */
class ContentTranslation extends AbstractPersonalTranslation
{

    /**
     * Convenient constructor
     *
     * @param string $locale
     * @param string $field
     * @param string $value
     */
    public function __construct($locale, $field, $value)
    {
        $this->setLocale($locale);
        $this->setField($field);
        $this->setContent($value);
    }

    /**
     * @ORM\ManyToOne(targetEntity="AppBundle\Entity\Content", inversedBy="translations")
     * @ORM\JoinColumn(name="object_id", referencedColumnName="id", onDelete="CASCADE")
     */
    protected $object;

    public function __toString()
    {
       return (string) $this->getName();
    }

}

```
I create form and try to submit translations. But this error appear. 

CRITICAL - Uncaught PHP Exception Doctrine\DBAL\Exception\TableNotFoundException: "An exception occurred while executing 'SELECT t0.id AS id_1, t0.locale AS locale_2, t0.object_class AS object_class_3, t0.field AS field_4, t0.foreign_key AS foreign_key_5, t0.content AS content_6 FROM ext_translations t0 WHERE t0.locale = ? AND t0.object_class = ? AND t0.field = ? AND t0.foreign_key IS NULL LIMIT 1' with params ["en", "AppBundle\\Entity\\Content", "title"]: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'zwiedzamdevdb.ext_translations' doesn't exist" at /home/michal/www/zwiedzam-admin-dev/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 53 

Any idea what can be wrong? 

It tries to look into ext_translations for some reason but it should look into zc_content_translations table.

**Comment by spdionis** [comment] 2017-01-19 09:29
Just a pointer, the issue is probably in https://github.com/Simettric/DoctrineTranslatableFormBundle/blob/master/Form/DataMapper.php#L52 .

**Comment by asiermarques** [comment] 2017-09-18 18:15
This is fixed now. Thank you!

I´ve updated the documentation.

**Closed as completed by asiermarques** 2017-09-18 18:15 UTC
